build:
  command: "pip install -r requirements.txt"
start: "gunicorn app:app"

services:
  - type: web
    name: smart-healthcare-chatbot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    autoDeploy: true
